package marine.conservation.enums;

public enum CertificationType {
    PADI_OPEN_WATER_DIVER,
    PADI_ADVANCED_OPEN_WATER,
    SCUBA_DIVING_CERTIFICATION,
    UNDERWATER_PHOTOGRAPHER,
    FIRST_AID_CPR,
    MARINE_BIOLOGY_CERTIFICATE,
    EMERGENCY_OXYGEN_PROVIDER,
    WILDLIFE_FIRST_RESPONDER,
    BOAT_LICENSE,
    VHF_RADIO_OPERATOR,
    CORAL_RESTORATION,
    MARINE_MAMMAL_OBSERVER,
    BASIC_VOLUNTEER_TRAINING,
    EVENT_SUPPORT
}
